### ISSUE TITLE
[User Story] Import car front photo from smartphone/computer folder/gallery

### ISSUE THREAD

**Issue by jimmyandrade** [multei/web#178]
### English

**As a** user who is creating a parking report
**I want to** select a photo from my smartphone/computer folder
**So that I** can use a photo that I had already taken (outside Multei!) 

### Portuguese (Brazil)

**Como** uma pessoa que está realizando uma denúncia
**Eu gostaria de** enviar uma imagem do rolo de câmera (ou pasta do dispositivo)
**De forma que eu** possa tirar a foto sem depender do app Multei! estar aberto

## Business context

Many users may decide to start a parking report after having already taken a photo, and wish to submit them either on their computer or on their smartphone. In order to permit users to do that without having to re-take a photo at the exact moment they start a report, we should offer the option to select and upload a photo from a folder.

We also consider the option of letting users take a photo from their camera at the moment they start the parking report, from within the Multei app (#177), but this is not a priority as it would not be possible from a computer.

## In scope

- [ ] Redirect focus to folder/pictures gallery
- [x] Show thumbnail of selected photo after the user returns to Multei.

## Out of scope
- Use the camera app (#177)
- Upload photo to API (#180)
- Validate the image (#180)

## Acceptance Criteria

- [x] **1. User sees photo gallery**  
      **Given** the user has read the instructions and wants to select a front car photo,
      **When** they click on "Selecionar foto",
      **Then** the smartphone/computer folder/gallery opens as a new window.
- [x] **2. User selects photo**  
      **Given** the user is at the photo gallery/folder,
      **When** the user has selected a photo from the gallery/folder,
      **Then** the photo is loaded on Multei interface (as a thumbnail/preview)
      
## Checklist do kickoff

- [x] A análise da história está concluída?
- [x] QA (ou pessoa que assumiu o papel de QA) revisou a análise?
- [x] A história está completa com todos os detalhes e as informações relevantes?  
  (Ex.: Contexto, Escopo, Fora de Escopo, Critérios de aceite, etc);
- [x] O valor de negócio da história está bem entendido? (se aplicável)
- [x] Esta história não tem dependência de outras histórias futuras?
- [x] Não existem dívidas técnicas (débitos técnicos) relacionadas a história;
- [x] Há protótipos de telas para essa história (se aplicável)
- [x] Há detalhes na história de mensagens de erro e outros feedbacks para o usuário (se aplicável)
- [x] Há mensagens de ajuda ou outros textos definidos na história (se aplicável)
- [x] A história está em um tamanho adequado
- [x] Existe feature toggle para a feature (se aplicável)

## Checklist do deskcheck

- [x] Há testes unitários que validem a implementação? (se aplicável)
- [x] As alterações de código passaram em todas as pipelines
- [x] A história foi executada manualmente
- [x] A história não trouxe regressões ou impacto negativo a outras implementações
- [x] Todos os critérios de aceite foram cobertos
- [x] A história não precisa de feedback ou correção
- [x] Foi testada uma jornada completa do usuário através da história (se aplicável)

**Comment by jimmyandrade** [comment]
@thomazmz temos algum _update_? Precisa de ajuda com algo?

**Comment by thomazmz** [comment]
![step-1](https://user-images.githubusercontent.com/16430263/84149026-30afb980-aa36-11ea-8fba-387bb3684c81.jpeg)

![step-2](https://user-images.githubusercontent.com/16430263/84149042-34434080-aa36-11ea-90a0-e888844b45ed.jpeg)

![step-3](https://user-images.githubusercontent.com/16430263/84149047-360d0400-aa36-11ea-8a5c-63611a4807cd.jpeg)

**Comment by thomazmz** [comment]
![step-1](https://user-images.githubusercontent.com/16430263/84149268-90a66000-aa36-11ea-98f4-ba43af9724e4.jpeg)

![step-2](https://user-images.githubusercontent.com/16430263/84149276-9308ba00-aa36-11ea-8d5c-a14e2b1b63a2.jpeg)

![step-3](https://user-images.githubusercontent.com/16430263/84149285-9734d780-aa36-11ea-8729-1da457509069.jpeg)
