### ISSUE TITLE
[User Story] Show validity message for car front photo

### ISSUE THREAD

**Issue by jimmyandrade** [multei/web#179]
## User story

Como uma pessoa que está realizando uma denúncia
Eu gostaria de saber se a foto que eu enviei é válida
De forma que a denúncia seja válida e tenha mais chances de qualificação

## Business context

A clear and concise description about the business context

**Is your feature request related to a problem? Please describe.**

**Describe alternatives you've considered**

## Items in scope of this issue

- [ ] Displays a message to the user asking them to send another photo if current is invalid;
- [ ] Do not allow the user to go to the next step until the photo is valid.

**Describe the solution you'd like**

## Out of scope

Items out of scope of this issue

## Additional context & notes

An invalid photo is a photo through which no car plate value can be completed.

## Acceptance Criteria

- [ ] **1. Acceptance title**  
      **Given** (…)  
      **When** (…)  
      **Then** (…)
- [ ] **2. Acceptance title**  
      **Given** (…)  
      **When** (…)  
      **Then** (…)  
      
## Checklist do kickoff

- [ ] A análise da história está concluída?
- [ ] QA (ou pessoa que assumiu o papel de QA) revisou a análise?
- [ ] A história está completa com todos os detalhes e as informações relevantes?  
  (Ex.: Contexto, Escopo, Fora de Escopo, Critérios de aceite, etc);
- [ ] O valor de negócio da história está bem entendido? (se aplicável)
- [ ] Esta história não tem dependência de outras histórias futuras?
- [ ] Não existem dívidas técnicas (débitos técnicos) relacionadas a história;
- [ ] Há protótipos de telas para essa história (se aplicável)
- [ ] Há detalhes na história de mensagens de erro e outros feedbacks para o usuário (se aplicável)
- [ ] Há mensagens de ajuda ou outros textos definidos na história (se aplicável)
- [ ] A história está em um tamanho adequado
- [ ] Existe feature toggle para a feature (se aplicável)

## Checklist do deskcheck

- [ ] Há testes unitários que validem a implementação? (se aplicável)
- [ ] As alterações de código passaram em todas as pipelines
- [ ] A história foi executada manualmente
- [ ] A história não trouxe regressões ou impacto negativo a outras implementações
- [ ] Todos os critérios de aceite foram cobertos
- [ ] A história não precisa de feedback ou correção
- [ ] Foi testada uma jornada completa do usuário através da história (se aplicável)

**Comment by tuliooassis** [comment]
A mensagem de erro e validação já foi implementada em #180.
