### ISSUE TITLE
[User Story] Car Front Photo verification

### ISSUE THREAD

**Issue by jimmyandrade** [multei/web#180]
## User story

As a user creating a parking report
I want to submit the car front photo
So that I'm able to move on with the parking report

## Business context

The user should submit a photo in the process of creating the parking report, if invalid this can not block the process. Therefore, the user must be able to submit a new photo to move on.

## In scope

- [x] User should be able to submit a car front photo when they click on "Avançar" button after seeing the thumbnail
- [x] If invalid, they should see the message "Por favor, envie uma foto da parte da frente do veículo." after they click on "Avançar" button
- [x] And they should be able to send the car front photo again

## Out of scope

- Custom error messages [#193]
- Reinforce the instructions about how to take a car front photo [#192]

## Acceptance Criteria

- [x] **1. User submit valid car front photo**  
      **Given** the user submit a valid car front photo
      **When** they click on "Avançar"
      **Then** the app shows a loading cog
      **And** the app should go to the next step

- [x] **2. User submit invalid car front photo**  
      **Given** the user submit an invalid car front photo
      **When** they click on "Avançar"
      **Then** the app shows a loading cog
      **And** the app shows the error message
      **And** allow the user to upload another photo

## Checklist do kickoff

- [x] A análise da história está concluída?
- [x] QA (ou pessoa que assumiu o papel de QA) revisou a análise?
- [x] A história está completa com todos os detalhes e as informações relevantes?  
  (Ex.: Contexto, Escopo, Fora de Escopo, Critérios de aceite, etc);
- [x] O valor de negócio da história está bem entendido? (se aplicável)
- [x] Esta história não tem dependência de outras histórias futuras?
- [x] Não existem dívidas técnicas (débitos técnicos) relacionadas a história;
- [x] Há protótipos de telas para essa história (se aplicável)
- [x] Há detalhes na história de mensagens de erro e outros feedbacks para o usuário (se aplicável)
- [x] Há mensagens de ajuda ou outros textos definidos na história (se aplicável)
- [x] A história está em um tamanho adequado
- [x] Existe feature toggle para a feature (se aplicável)

## Checklist do deskcheck

- [x] Há testes unitários que validem a implementação? (se aplicável)
- [x] As alterações de código passaram em todas as pipelines
- [x] A história foi executada manualmente
- [x] A história não trouxe regressões ou impacto negativo a outras implementações
- [x] Todos os critérios de aceite foram cobertos
- [x] A história não precisa de feedback ou correção
- [x] Foi testada uma jornada completa do usuário através da história (se aplicável)

**Comment by tuliooassis** [comment]
O card está bloqueado devido a um erro na biblioteca do OpenALPR do Multei. A biblioteca não consegue identificar a secretKey enviada como parâmetro.

**Comment by tuliooassis** [comment]
Há um possível trecho de código em useStepsNavigation que poderá ser refatorado para uma melhor abordagem.
