### ISSUE TITLE
🐛 [Bug] Photo did not remain when pressing the cancel button in the photo gallery

### ISSUE THREAD

**Issue by lemenezes** [multei/web#230]
## Description

The error happens when the user selects a photo but thinks about changing it. When opening the window to select a new photo and regret it, clicking cancel, the previous photo disappears.

## Steps to reproduce the behavior:

1. Go to 'http://multei.com.br/';
2. Click on 'FAZER DENÚNCIA ANÔNIMA';
3. Click on 'ADICIONAR FOTO' and select one;
4. Click on 'TROCAR FOTO' and click cancel the operation
5. See error: there is no photo preview.

## Expected behavior

When the user cancel instead of select a photo, the previous photo should keep selected.

## Screenshots

![image](https://user-images.githubusercontent.com/17442350/84078053-a112f800-a9ae-11ea-82eb-1240d1f221b9.png)

## Desktop:
 - OS:  macOS Catalina 10.15.4 (19E287)
 - Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

## Acceptance criteria

 - [x] 1. User should find the previous photo when cancel a change process
       **Given**  the user already selected one photo
       **When**  they click on 'TROCAR FOTO'
       **And**  click on 'CANCEL'
       **Then**  they should see the previous one 

## Test scenarios

- [x] Try to select one photo and change this one some times alternating between select another and cancel

## Checklist do kickoff

- [x] A análise da história está concluída?
- [x] QA (ou pessoa que assumiu o papel de QA) revisou a análise?
- [x] A história está completa com todos os detalhes e as informações relevantes?  
  (Ex.: Contexto, Escopo, Fora de Escopo, Critérios de aceite, etc);
- [x] O valor de negócio da história está bem entendido? (se aplicável)
- [x] Esta história não tem dependência de outras histórias futuras?
- [x] Não existem dívidas técnicas (débitos técnicos) relacionadas a história;
- [x] Há protótipos de telas para essa história (se aplicável)
- [x] Há detalhes na história de mensagens de erro e outros feedbacks para o usuário (se aplicável)
- [x] Há mensagens de ajuda ou outros textos definidos na história (se aplicável)
- [x] A história está em um tamanho adequado
- [x] Existe feature toggle para a feature (se aplicável)

## Checklist do deskcheck

- [x] Há testes unitários que validem a implementação? (se aplicável)
- [x] As alterações de código passaram em todas as pipelines
- [x] A história foi executada manualmente
- [x] A história não trouxe regressões ou impacto negativo a outras implementações
- [x] Todos os critérios de aceite foram cobertos
- [x] A história não precisa de feedback ou correção
- [x] Foi testada uma jornada completa do usuário através da história (se aplicável)

**Comment by tuliooassis** [comment]
Não foram implementados testes significativos para a alteração por ser pensado uma refatoração futura que simplificará o processo.

**Comment by tuliooassis** [comment]
Foram realizados testes manuais e a solução não trouxe regressões. 
Vale ressaltar que ainda há a falta de testes para validar a solução em si.
