### ISSUE TITLE
Refactor car reporting wizard steps hook

### ISSUE THREAD

**Issue by tuliooassis** [multei/web#241]
## Developer story

**Como** pessoa desenvolvedora
**Eu gostaria** de concentrar o uso de steps da aplicação em um único lugar
**De forma** que o uso de feature toggles
**E** adição de steps sejam facilmente implementadas

## Business context

Manter o escopo de gerenciamento de steps em um único local, como hook, por exemplo, facilitaria o desenvolvimento de novos steps e evitaria possíveis bugs no processo.

## In scope (technical checklist)

- [x] criar um hook responsável por fornecer todos os steps e informações relacionadas, como feature toggles e respectivos componentes
- [x] refatorar o container CarReportingWizard de forma a utilizar o novo hook
- [x] refatorar renderStepContent e getSteps de forma a utilizar o novo hook

## Acceptance Criteria

- [x] **1. Todos os testes continuam passando**  
      **Dado** a refatoração completa
      **Quando** os testes forem executados
      **Então** todos os testes devem passar
- [x] **2. A cobertura de testes deve continuar a mesma ou maior**  
      **Dado** uma cobertura de testes
      **Quando** a refatoração for finalizada
      **Então** a cobertura de testes deve continuar a mesma
      
## Checklist do kickoff

- [x] A análise da história está concluída?
- [x] QA (ou pessoa que assumiu o papel de QA) revisou a análise?
- [x] A história está completa com todos os detalhes e as informações relevantes?  
  (Ex.: Contexto, Escopo, Fora de Escopo, Critérios de aceite, etc);
- [x] O valor de negócio da história está bem entendido? (se aplicável)
- [x] Esta história não tem dependência de outras histórias futuras?
- [x] Não existem dívidas técnicas (débitos técnicos) relacionadas a história;
- [x] Há protótipos de telas para essa história (se aplicável)
- [x] Há detalhes na história de mensagens de erro e outros feedbacks para o usuário (se aplicável)
- [x] Há mensagens de ajuda ou outros textos definidos na história (se aplicável)
- [x] A história está em um tamanho adequado
- [x] Existe feature toggle para a feature (se aplicável)

## Checklist do deskcheck

- [x] Há testes unitários que validem a implementação? (se aplicável)
- [x] As alterações de código passaram em todas as pipelines
- [x] A história foi executada manualmente
- [x] A história não trouxe regressões ou impacto negativo a outras implementações
- [x] Todos os critérios de aceite foram cobertos
- [x] A história não precisa de feedback ou correção
- [x] Foi testada uma jornada completa do usuário através da história (se aplicável)

**Comment by jimmyandrade** [comment]
@tuliooassis depois adiciona um Developer Story pra gente? :)

**Comment by tuliooassis** [comment]
Uma possível melhoria futura a avaliar seria adicionar a possibilidade do uso de _useFeatureToggles_ de forma a obter todas as feature toggles do sistema.
Por exemplo: ` const [ toggles, setToggles ] = useFeatureToggles()`
