### ISSUE TITLE
Home figure does not have a text description

### ISSUE THREAD

**Issue by adalbertomaia** [multei/web#57]
## Description
Picture at home does not have a text description.

## Steps to reproduce the behavior:
1. Navigate to `/`;
2. Inspect the image;
3. Run aXe audit;
4. See missing `alt` attribute error;

## Expected behavior
Figure should have a `alt` attribute

## Screenshots
![image](https://user-images.githubusercontent.com/23324060/75887091-041d4d80-5e08-11ea-903d-147f419c57fe.png)

![image](https://user-images.githubusercontent.com/23324060/75887292-578f9b80-5e08-11ea-8ccb-1e590613e369.png)

**Comment by jimmyandrade** [comment]
@all-contributors please add @adalbertomaia for bug

**Comment by jimmyandrade** [comment]
@all-contributors please add @adalbertomaia for a11y

**Comment by jimmyandrade** [comment]
@all-contributors please add @jimmyandrade for a11y
